#!/usr/bin/env php
<?php

require __DIR__ . '/vendor/autoload.php';
require __DIR__ . '/app/container.php';

use Symfony\Component\Console\Application;

$application = new Application();

$application->add($container->get(\WemsCA\Command\DatabaseCommand::class));

$application->run();
