---
ca_path: /home/ben/projects/work/ssh_ca/dev_em_auth_unsigned

# optional
tmp_dir: /tmp
default_expiry: 1h
default_login_user: wems
permissions:
  - "permit-pty"
  - "force-command=df"
certificate_identity: signed by WEMS dev-em CA

# psr-3 log levels (ala syslog)
log_level: notice
